services:

  util-umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: util-umami
    restart: unless-stopped
    ports:
      - 10006:3000
    environment:
      DATABASE_URL: postgresql://umami:umami@util-umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
    depends_on:
      util-umami-db:
        condition: service_healthy
    init: true
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  util-umami-db:
    image: postgres:15-alpine
    container_name: util-umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - './umami-db-data:/var/lib/postgresql/data'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
