services:

  util-traefik:
    image: traefik:latest
    container_name: util-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - './traefik-data/acme.json:/acme.json'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - 80:80
      - 443:443
      - 10000:8080
    environment:
      - TZ=${TIMEZONE}
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=debug
      # docker provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # letsencrypt dns challenge
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.disablePropagationCheck=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=60
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1
      # redirect http to https
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      # https configuration
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=favo02.dev
      - --entrypoints.websecure.http.tls.domains[0].sans=*.favo02.dev

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.util-traefik.rule=Host(`traefik.favo02.dev`)"
      - "traefik.http.services.util-traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.util-traefik.entrypoints=websecure"
      - "traefik.http.routers.util-traefik.tls=true"
      - "traefik.http.routers.util-traefik.tls.certresolver=letsencrypt"


