services:

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: service-immich-app
    restart: unless-stopped
    volumes:
      - './library-data:/usr/src/app/upload'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - TZ=${TZ}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    # connection is permitted only through reverse proxy
    # ports:
    #   - 55555:2283
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    networks:
      - default
      - traefik_proxy05
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_proxy05'
      - 'traefik.http.routers.service-immich.rule=Host(`immich.favo02.dev`) || Host(`photos.favo02.dev`)'
      - 'traefik.http.services.service-immich.loadbalancer.server.port=2283'
      - 'traefik.http.routers.service-immich.entrypoints=webs-in,webs-ex'
      - 'traefik.http.routers.service-immich.tls.certresolver=letsencrypt'

  immich-machine-learning:
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: release-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: service-immich-ml
    restart: unless-stopped
    volumes:
      - './ml-cache-data:/cache'
    environment:
      - TZ=${TZ}
    healthcheck:
      disable: false
    networks:
      - default

  redis:
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    container_name: service-immich-redis
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - default

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    container_name: service-immich-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - './database-data:/var/lib/postgresql/data'
    networks:
      - default

networks:
  default:
  traefik_proxy05:
    external: true
