services:

  util-authelia:
    image: authelia/authelia:latest
    container_name: util-authelia
    restart: unless-stopped
    ports:
      - 10000:9091
    volumes:
      - './authelia-data/config:/config'
