services:

  vpn:
    image: linuxserver/wireguard:latest
    container_name: util-wireguard
    restart: unless-stopped
    ports:
      - 51820:51820/udp
    volumes:
      - './wireguard-data:/config'
      - '/lib/modules:/lib/modules'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
      SERVERURL: ${DOMAIN}
      PEERS: ${PEERS}
      PEERDNS: auto
      ALLOWEDIPS: ${ALLOWEDIPS}
