services:

  website-seelabel:
    container_name: website-seelabel
    build: ./src-data
    restart: unless-stopped
    ports:
      - 3004:8000
    environment:
      - MODEL_NAME=yolov9e-seg.pt
   #  - MODEL_NAME=yolov8x-seg.pt
