services:

  app:
    image: fireflyiii/core:latest
    container_name: service-firefly-app
    restart: unless-stopped
    # connection is permitted only through reverse proxy
    # ports:
    #   - 55555:8080
    volumes:
      - './firefly-upload-data:/var/www/html/storage/upload'
    environment:
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - TZ=${TZ}
      - STATIC_CRON_TOKEN=${STATIC_CRON_TOKEN}
    depends_on:
      - db
    networks:
      - default
      - traefik_proxy04
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_proxy04'
      - 'traefik.http.routers.service-firefly.rule=Host(`firefly.favo02.dev`)'
      - 'traefik.http.services.service-firefly.loadbalancer.server.port=8080'
      - 'traefik.http.routers.service-firefly.entrypoints=webs-in,webs-ex'
      - 'traefik.http.routers.service-firefly.tls.certresolver=letsencrypt'

  db:
    image: mariadb:latest
    container_name: service-firefly-db
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './firefly-db-data:/var/lib/mysql'
    networks:
      - default

  cron:
    image: alpine:latest
    container_name: service-firefly-cron
    restart: unless-stopped
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - default

networks:
  default:
  traefik_proxy04:
    external: true
