services:

  app:
    image: fireflyiii/core:latest
    container_name: service-firefly-app
    restart: unless-stopped
    # connection is permitted only through reverse proxy
    # ports:
    #   - 55555:8080
    volumes:
      - './firefly-upload-data:/var/www/html/storage/upload'
    env_file: .env
    depends_on:
      - db
    networks:
      - default
      - traefik_proxy04
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_proxy04'
      - 'traefik.http.routers.service-firefly.rule=Host(`firefly.favo02.dev`)'
      - 'traefik.http.services.service-firefly.loadbalancer.server.port=8080'
      - 'traefik.http.routers.service-firefly.entrypoints=websecure'
      - 'traefik.http.routers.service-firefly.tls.certresolver=letsencrypt'

  db:
    image: mariadb:latest
    container_name: service-firefly-db
    restart: unless-stopped
    env_file: .db.env
    volumes:
      - './firefly-db-data:/var/lib/mysql'
    networks:
      - default

  cron:
    image: alpine:latest
    container_name: service-firefly-cron
    restart: unless-stopped
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - default

networks:
  default:
  traefik_proxy04:
    external: true
