services:

  superunimia:
    image: ghcr.io/favo02/super-unimia:latest
    container_name: website-superunimia
    restart: unless-stopped
    # connection is permitted only through reverse proxy
    # ports:
    #   - 55555:80
    networks:
      - traefik_proxy08
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_proxy08'
      - 'traefik.http.routers.website-superunimia.rule=Host(`superunimia.favo02.dev`)'
      - 'traefik.http.services.website-superunimia.loadbalancer.server.port=80'
      - 'traefik.http.routers.website-superunimia.entrypoints=webs-in,webs-ex'
      - 'traefik.http.routers.website-superunimia.tls.certresolver=letsencrypt'

networks:
  traefik_proxy08:
    external: true
