services:

  website-cessadvisorapi:
    build: ./src-data
    container_name: website-cessadvisorapi
    restart: unless-stopped
    ports:
      - 3003:3000
    volumes:
      - './logs-data:/app/logs'
