services:

  gotify:
    image: gotify/server:latest
    container_name: util-gotify
    restart: unless-stopped
    # connection is permitted only through reverse proxy
    # ports:
    #   - 55555:80
    volumes:
      - './gotify-data:/app/data'
    environment:
      TZ: ${TIMEZONE}
    networks:
      - traefik_proxy02
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_proxy02'
      - 'traefik.http.routers.util-gotify.rule=Host(`gotify.favo02.dev`) || Host(`push.favo02.dev`)'
      - 'traefik.http.services.util-gotify.loadbalancer.server.port=80'
      - 'traefik.http.routers.util-gotify.entrypoints=websecure'
      - 'traefik.http.routers.util-gotify.tls.certresolver=letsencrypt'

networks:
  traefik_proxy02:
    external: true
