services:

  util-pihole:
    image: pihole/pihole:latest
    container_name: util-pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 10002:80/tcp
    volumes:
      - './pihole-data:/etc/pihole'
      - './dnsmasq-data:/etc/dnsmasq.d'
    environment:
      TZ: ${TIMEZONE}
